name: "Test-GitHub-Action"
description: "This a sample github action."
author: "nazir"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "heart"
  color: "red"

# Define your inputs here.
inputs:
  appId:
    description: "AAD AppId."
    required: true

  appSecret:
    description: "AAD App Secret."
    required: true

  keyVaultName:
    description: "KeyVault Name."
    required: true

  tenantId:
    description: "AADTenantId."
    required: true

  secretName:
    description: "Secret Name."
    required: true

# Define your outputs here.
outputs:
  time:
    description: "Execution finish time."

runs:
  using: node20
  main: dist/index.js
